
# Define settings, that apply for all codechunks
```{r include = FALSE}
knitr::opts_chunk$set(
  echo  =  FALSE, # Code within codechunk will not be displayed as a general rule
  fig.show  =  TRUE, # Figures will be displayed as a general rule
  message  =  FALSE, # Messages generated by R/RStudio will not be displayed as a general rule
  warning  =  FALSE, # Warnings generated by R/RStudio will not be displayed as a general rule
  fig.pos = 'H' # Within the dynamic report, any figure produced by code will be displayed directly at the
  # position of the respective code
)
options(tinytex.verbose = TRUE)
```

# Create a function, that defines the size of text generated from codechunks
```{r}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk  =  function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size  !=   "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

# Include a .png file in the dynamic report (.rmd-file)
```{r SomePNG, out.width = "50%"}
knitr::include_graphics("SomePNG.png")
```

# Create a Codechunk called "RandomCodeChunk", where the size of text ist "scriptsize"
```{r RandomCodeChunk, size = "scriptsize"}

```

# Create a chodechunk, whose code is not echoed in the report that is being knitted,
# but whose results are included
```{r echo = FALSE}

```

# Create a codechunk, where neither its' code nor its' results are knitted 
```{r include = FALSE}

```

# Create a codechunk, whose figures graphs and further are included when
# the report is knitted, even if the default has been set to "hide" 
```{r fig.show='asis'}

```
# Create a custom caption for all figures and plot generated within the same code chunk
# The Caption includes a reference-pointer, so that the figures as a whole can be referenced later
```{r fig.cap = "\\label{fig:fig1}Some Histograms.Own Representation."}

```

# Set the height and width of all the figures and plots generated within this code chunk
```{r fig.height=3, fig.width=6}

```





